version: "3.9"
services:
  help:
    # SeQ is a framework for logging of exceptions etc
    container_name: webshophelp
    image: benj3249/webshophelp
    restart: unless-stopped
    ports:
      - 8000:8080     
    networks:
      - backtier
    environment:
      - SERVER=webshopdatabase
  seq:
    # SeQ is a framework for logging of exceptions etc
    container_name: SeQ
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - 8081:80
      - 5341:5341
    networks:
      - backtier
    environment:
      - ACCEPT_EULA=Y
  smtp4dev:
    # Development time email server and client, easy to test sending emails
    container_name: smtp4dev
    image: rnwood/smtp4dev:latest
    ports:
      - 8082:80
      - 26:25
    networks:
      - backtier
  paymentapi:
    # The payment API
    container_name: webshop.payment
    image: benj3249/webshoppaymentapi
    restart: unless-stopped
    ports:
      - 8083:8080
    networks:
      - backtier  
  catalogapi:
    # The catalog API
    container_name: webshop.catalog
    image: benj3249/webshopcatalogapi
    restart: unless-stopped
    ports:
      - 8084:8080
    networks:
      - backtier
  customerapi:
    # The customer API
    container_name: webshop.customer
    image: benj3249/webshopcustomerapi
    restart: unless-stopped
    ports:
      - 8085:8080
    networks:
      - backtier
  reviewapi:
    # The review API
    container_name: webshop.review
    image: benj3249/webshopreviewservice
    restart: unless-stopped
    ports:
      - 8086:8080
    networks:
      - backtier
    environment:
      - connectionstring=Server=webshopdatabase;Database=PSUReviews;User Id=sa;Password=PSU@password
  sqlexpress:
    # The SQL server
    container_name: webshopdatabase
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    ports:
      - 1403:1433 # SQL Server port, connect SSMS with this: localhost, 1403
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PSU@password
      - MSSQL_PID=Express
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - backtier
  rabbitmq:
    # RabbitMQ service with management plugin
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672 # RabbitMQ messaging port
      - 15672:15672 # RabbitMQ management UI port
    networks:
      - backtier
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 8087:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - backtier
networks:
  backtier: {}
