# .github/workflows/build_and_deploy.yml
name: Build and Deploy Service

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string
      docker-tag:
        required: true
        type: string
      DOCKER_HUB_USERNAME:
        required: true
        type: secret
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
        type: secret

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Docker login step with secrets explicitly passed as inputs
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKER_HUB_USERNAME }}
        password: ${{ inputs.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.service-path }}

    - name: Build
      run: dotnet build ${{ inputs.service-path }} --no-restore

    - name: Test
      run: dotnet test ${{ inputs.service-path }} --no-build --verbosity normal

    - name: Publish
      run: dotnet publish ${{ inputs.service-path }}

    - name: Build Docker image
      run: docker build -f ${{ inputs.service-path }}/Dockerfile --force-rm -t ${{ inputs.docker-tag }} --build-arg "BUILD_CONFIGURATION=Debug" .

    - name: Push Docker image
      run: docker push ${{ inputs.docker-tag }}
