on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  build_test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        service_path:
          - Webshop.Catalog.Solution/Webshop.Review.API/Webshop.Review.API.csproj
          - Webshop.Catalog.Solution/Webshop.Payment.Api/Webshop.Payment.Api.csproj
          - Webshop.Catalog.Solution/Webshop.Customer.Api/Webshop.Customer.Api.csproj
          - Webshop.Catalog.Solution/Webshop.Catalog.Api/Webshop.Catalog.Api.csproj
          - Webshop.Catalog.Solution/Webshop.Help/Webshop.Help.csproj
          - Webshop.Catalog.Solution/Webshop.ReviewServiceGateway/Webshop.ReviewServiceGateway.csproj
    steps:
    - uses: actions/checkout@v3

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.service_path }}

    - name: Build
      run: dotnet build ${{ matrix.service_path }} --no-restore

    - name: Test
      run: dotnet test ${{ matrix.service_path }} --no-build --verbosity normal

  publish_docker:
    needs: build_test
    strategy:
      matrix:
        service_path:
          - Src/API/Webshop.Review.API
          - Src/API/Webshop.Payment.Api
          - Src/API/Webshop.Customer.Api
          - Src/API/Webshop.Catalog.Api
          - Src/Webshop.Help
        image_name:
          - benj3249/webshopreviewservice
          - benj3249/webshoppaymentapi
          - benj3249/webshopcustomerapi
          - benj3249/webshopcatalogapi
          - benj3249/webshophelp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build -f ${{ matrix.service_path }}/Dockerfile --force-rm -t ${{ matrix.image_name }}:latest --build-arg "BUILD_CONFIGURATION=Debug" Src

    - name: Push Docker image
      run: docker push ${{ matrix.image_name }}:latest
