# .github/workflows/webshop_build.yml
name: Webshop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test_solution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
        restore-keys: |
          nuget-
    - name: Restore dependencies
      run: dotnet restore Webshop.Catalog.Solution/Webshop.Solution.sln
    - name: Build
      run: dotnet build Webshop.Catalog.Solution/Webshop.Solution.sln --no-restore
    - name: Test
      run: dotnet test Webshop.Catalog.Solution/Webshop.Solution.sln --no-build --verbosity normal

    # Add Docker login here to ensure authentication in this workflow
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  # Call the reusable workflow for each microservice

  build_deploy_review_service:
    needs: build_test_solution
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      service-path: Webshop.Catalog.Solution/Webshop.Review.API/Webshop.Review.API.csproj
      docker-tag: benj3249/webshopreviewservice:latest

  build_deploy_payment_service:
    needs: build_test_solution
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      service-path: Webshop.Catalog.Solution/Webshop.Payment.Api/Webshop.Payment.Api.csproj
      docker-tag: benj3249/webshoppaymentapi:latest

  build_deploy_customer_service:
    needs: build_test_solution
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      service-path: Webshop.Catalog.Solution/Webshop.Customer.Api/Webshop.Customer.Api.csproj
      docker-tag: benj3249/webshopcustomerapi:latest

  build_deploy_catalog_service:
    needs: build_test_solution
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      service-path: Webshop.Catalog.Solution/Webshop.Catalog.Api/Webshop.Catalog.Api.csproj
      docker-tag: benj3249/webshopcatalogapi:latest

  build_deploy_help:
    needs: build_test_solution
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      service-path: Webshop.Catalog.Solution/Webshop.Help/Webshop.Help.csproj
      docker-tag: benj3249/webshophelp:latest

  build_deploy_gateway:
    needs: build_test_solution
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      service-path: Webshop.Catalog.Solution/Webshop.ReviewServiceGateway/Webshop.ReviewServiceGateway.csproj
      docker-tag: benj3249/webshopgateway:latest
